export default {
    products:[ {
        _id:'1',
            name:'Slim shirt',
            category:'Shirts',
            image:'/images/1.jpg',
            price:60,
            brand:'Nike',
            rating:4.5,
            numReviews:10,
            countInStock:6
        },

        {   _id:'2',
            name:'Best Pants',
            category:'Shirts',
            image:'/images/2.jpg',
            price:57,
            brand:'Nike',
            rating:4.5,
            numReviews:5,
            countInStock:4
        },

        {   _id:'3',
            name:'Fit shirt',
            category:'Shirts',
            image:'/images/3.jpg',
            price:50,
            brand:'Nike',
            rating:3.5,
            numReviews:10,
            countInStock:6,
        },

        {   _id:'4',
        name:'Fit pants',
        category:'Shirts',
        image:'/images/4.jpg',
        price:50,
        brand:'Nike',
        rating:3.5,
        numReviews:10,
        countInStock:7,
    },

    {   _id:'5',
    name:'Big shirt',
    category:'Shirts',
    image:'/images/5.jpg',
    price:50,
    brand:'Nike',
    rating:3.5,
    numReviews:10,
    countInStock:6,
},

{   _id:'6',
name:'small shirt',
category:'Shirts',
image:'/images/6.jpg',
price:50,
brand:'Nike',
rating:3.5,
numReviews:10,
countInStock:6,
}
    ]
}